platform :ios, '10.0'

target "alleycat" do
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'React', :path => '../node_modules/react-native', :subspecs => ['DevSupport']
end
